heat_template_version: 2013-05-23

description: Deploy a new Asterisk node 

parameters:
  instance_name:
    type: string
    label: Instance Name
    description: Name of the compute instance
  key_name:
    type: string
    label: Key Name
    description: Name of key-pair to be used for compute instance
  image_name:
    type: string
    label: Image Name
    description: Image to be used for compute instance
  flavor_name:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
  private_network_id:
    type: string
    label: Private Network Id
    description: Private network to be used for compute instance
  public_network_id:
    type: string
    label: Public Network Id
    description: Public network to be used for compute instance
  security_group_id:
    type: string
    label: Security Group Id
    description: Security group to be used


resources:
  instance1_port0:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_param: private_network_id } 
      security_groups:
        - { get_param: security_group_id }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_network_id } 

  floating_ip_assoc:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: floating_ip }
      port_id: { get_resource: instance1_port0 }

  instance1:
    type: OS::Nova::Server
    properties:
      name: { get_param: instance_name }
      key_name: { get_param: key_name }
      image: { get_param: image_name }
      flavor: { get_param: flavor_name }
      networks:
        - port: { get_resource: instance1_port0 }

outputs:
  instance1_ip:
    description: Private IP address of the deployed instance
    value: { get_attr: [instance1, first_address] }